.\"                                      Hey, EMACS: -*- nroff -*-
.TH TSERIES 1 "May 11, 2016"
.SH NAME
tseries \- MET Norway time series viewer
.SH SYNOPSIS
.B tseries
.I [ -s setupfile ]
.I [ -S site ]
.I [ -l lang ]
.I [ -T title ]
.I [ -I instancename ]
.I [ -H wdbhost ]
.I [ -u wdbuser ]
.I [ -d section1:key1=token1 section2:key2=token2 ]
.SH DESCRIPTION
Tseries is a time series viewer for weather forecasts and observations.
Please use
.B tseries -h
for help.
.SH AUTHOR
Tseries was written at Met.no, the Norwegian Meteorological
Institute. This manual page was written by Alexander B\(:urger
<alexander.buerger@met.no> in May 2016.
